[feat] Add ci-dashboard-server with attached database
mayadata-io/ci-e2e-status pull request #3
Opened 2019-02-27 06:03 UTC by chandankumar4

This commit will do following:-

1 - Postgres database used for store all details
2 - Featch build pipeline and jobs data from gitlab and store it to
databse
3 - Fetch GKE, AKS, and EKS platforms pipeline and jobs data from gitlab
and stored it to respective table
4 - Total table created in database are following..
    - buildpipeline
    - buildjobs
    - gkepipeline
    - gkejobs
    - akspipeline
    - aksjobs
    - ekspipeline
    - eksjobs

5 - Total endpoint hosted by server
    - /build (build related data available)
    - /gke (gke platform related data available)
    - /eks (eks platform related data available)
    - /aks (aks platform related data available)

Signed-off-by: Chandan Kumar <chandan.kumar@mayadata.io>

2019-02-27 06:10 UTC, inyee786 requested changes

2019-02-27 06:10 UTC, inyee786 commented on k8s/deployment.yaml
> +        image: chandankumar4/database:latest
change chandankumar4/database:latest to {openebs/mayadataio}/{docker hub repo}

2019-03-05 10:48 UTC, mayavuser approved these changes
LGTM

2019-03-05 11:28 UTC, inyee786 approved these changes
LGTM

2019-03-05 11:31 UTC, merged